site_name: Pydoxtools
site_url: https://www.github.com/Xyntopia/pydoxtools
repo_url: https://www.github.com/Xyntopia/pydoxtools
nav:
    - Home: README.md
theme: readthedocs

plugins:
  - search
  - mkdocstrings

extra:
  readme: ./README.md

