site_name: Pydoxtools
site_url: https://xyntopia.github.io/pydoxtools
repo_url: https://www.github.com/xyntopia/pydoxtools
nav:
  - Introduction: index.md
  - Readme: readme_cp.md
  - Examples: examples.md
  - Reference:
    - Document: document.md
    - DocumentBag: documentbag.md
    - Other Classes: reference.md

theme:
  name: material
  palette:
    primary: custom
  #logo: assets/logo.png
  #favicon: images/favicon.png # not sure if we need this


watch:
  - pydoxtools
  - docs


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            docstring_style: google
          paths: [pydoxtools]  # search packages in the src folder

extra:
  readme: ./README.md
  analytics:
    provider: google
    property: G-27JXS58V30
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - css/mkdocstrings.css
  - stylesheets/extra.css



