site_name: Pydoxtools
site_url: https://www.github.com/Xyntopia/pydoxtools
repo_url: https://www.github.com/Xyntopia/pydoxtools
nav:
    - Home: index.md
    - Readme: readme_cp.md
#theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

extra:
  readme: ./README.md

